# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'


test:
  adapter: postgresql
  encoding: unicode
  database: testapp_test
  host: localhost
 
development:
  adapter: postgresql
  encoding: unicode
  database: testapp_development
  host: localhost